# Generated by Django 5.2.1 on 2025-06-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=20)),
                ('join_date', models.DateField()),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
